package gr.entij.event;

import gr.entij.Entity;

/**
 * Base class for all events generated by, or related to, entities.
 */
public class Event {
    
    /**
     * The entity for which the event was generated.
     */
    public final Entity source;
    
    /**
     * The move that caused the action which generated the event.
     * {@code null} if the event was not generated directly by a call to
     * {@link Entity#move}.
     * @see Entity#move
     */
    public final Object move;
    
    public Event(Entity source) {
        this(source, null);
    }

    public Event(Entity source, Object move) {
        this.source = source;
        this.move = move;
    }

    @Override
    public String toString() {
        return super.toString()+" source: ["+source+"]";
    }
}
