package gr.entij.event;

import gr.entij.Entity;

/**
 * Base class for all events generated by, or related to, entities.
 */
public class Event {
    
    /**
     * The entity for which the event was generated.
     */
    public final Entity source;
    
    public Event(Entity source) {
        this.source = source;
    }

    @Override
    public String toString() {
        return super.toString()+" source: "+source;
    }
}
